project:
  type: website
  output-dir: "docs"

website:
  title: "Ubit Info"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Accueil
      - href: formation.qmd
        text: Formation
      - href: reparation.qmd
        text: Reparation & Decodage
      - href: contact.qmd
        text: Contact
        
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

